Fix tag editor on Android R+
VinylMusicPlayer/VinylMusicPlayer pull request #864
Opened 2023-11-25 10:53 UTC by MageFroh

Simply moved the call to the new Android R `MediaStore.createWriteRequest` to `writeValuesToFiles`, in the case where SD Card access is not granted.

I've also reworked the logic in `writeValuesToFiles` to make it more linear.

Need to double-check everything is fine on these Android versions:

- [ ] Prior to Lollipop
- [ ] Lollipop+ (but prior to R)
- [x] R+ (tested on Tiramisu)

2023-11-25 10:54 UTC, MageFroh commented
Related to #863

2023-11-25 11:43 UTC, MageFroh commented
I can't try this with KitKat: the tag editor is completely broken due to another problem.
The app crashes due to:
```
Could not find class 'java.nio.file.OpenOption[]', referenced from method org.jaudiotagger.audio.flac.FlacTagWriter.write
```
https://developer.android.com/reference/java/nio/file/OpenOption mentions that it's been added in API 26 (Oreo).

This completely breaks `AudioFileIO`, so basically, I think the tag editor is simply not available on Nougat and earlier 😅

What should we do about this? Simply remove the tag editor option on these old versions? Leave this for now, in another issue?
I'm not sure we'll get jaudiotagger updated: the project does not seem very alive...

2023-11-25 15:36 UTC, soncaokim commented
Thanks for the work.

> What should we do about this?

I'd remove the tag editor option then

2023-11-25 18:00 UTC, soncaokim commented
> I'm not sure we'll get jaudiotagger updated: the project does not seem very alive...

There is this one - https://github.com/wseemann/FFmpegMediaMetadataRetriever - probably worth a look....

2023-11-26 22:54 UTC, ZashIn commented
For another reference, this seems to be still working, too: https://github.com/vanilla-music/vanilla-music-tag-editor

2023-11-27 12:39 UTC, MageFroh commented
Interesting, I've got the same version of Android and didn't see any issue.
Which tag did you try to change?
Did you see a popup asking for permission to write to the audio file?

I'll try to reproduce this.
Am I right that you didn't do a clean reinstall of vinyl since it's been migrated to the recent SDK?

2023-11-27 13:31 UTC, canon-benoit-lecardonnel commented
Thanks that helps

I've done clean install only so far - I can easily try to do a non-clean install to see if it reproduces this issue then.

2024-01-01 05:31 UTC, gaycodegal commented
hello, I believe this issue is happening because `!SAFUtil.isSAFRequired(savedSongs)` is evaluating to `true` (saf not required) which doesnt happen on my device but theoretically could.

- Prevously (before this PR) AND after API 30, SAF is assumed to be required by default and `SAFUtil.isSAFRequired` would never be called.
- If SAF is called and writeTags is called instead of writeTagsApi30, this will cause the reported issue. 
    - `MediaStore.createWriteRequest` will NOT be called and instead the AsyncTask.doInBackground will be called without first getting permissions. 
    - This will likely lead to a crash like the one reported.

To fix:

```java
if (Build.VERSION.SDK_INT < VERSION_CODES.R && !SAFUtil.isSAFRequired(savedSongs)) {
   writeTags(savedSongs);
} else ... 
```

Just a note, this may imply the PR will also crash if the SD card access is granted and the app is trying to edit a file not on the SD card. Potential issues there as well but unclear to me. I havent reviewed what happens as I dont have an SD capable device and dont know how the app reacts to those.

I would also recommend renaming AsyncTask perhaps to something like AsyncTagWriterTask or something more clear as to its purpose but this is not required.

2024-01-01 05:51 UTC, gaycodegal commented
reviewing further, the sd card thing does seem do do some weird Uri math so it hopefully wont cause a crash in the instance I describe, but it is a bit unclear to me.

2024-01-01 05:56 UTC, gaycodegal commented
Also if the purpose of this PR is not a refactor and just to fix the underlying issue, would it work to just do 

```java
} else {
  if (SAFUtil.isSDCardAccessGranted(this)) {
      writeTags(savedSongs);
  }
}
```
to 
```java
} else {
  writeTags(savedSongs);
}
```
instead of this whole refactor? It fixes the issue for me, and the isSDCardAccessGranted is not load bearing (no side effects).

2024-01-24 15:39 UTC, soncaokim commented
@MageFroh any update on this PR please?

2024-02-21 14:36 UTC, soncaokim commented
Hi, is this PR still relevant?

2024-02-23 11:59 UTC, MageFroh commented
I'm not planning to do more in this area, so closing this PR.

2024-02-23 11:59 UTC, closed without merging

2024-07-13 10:39 UTC, GregKruz requested changes
Hack